name: Ubuntu Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xrdp and configure for root
        run: |
          # 安裝 xrdp
          sudo apt-get update
          sudo apt-get install -y xrdp

          # 配置 xrdp 使用 root 用戶
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config

          # 為 root 用戶設置一個安全的密碼
          echo 'root:yangzx@01' | sudo chpasswd

      - name: Install ngrok
        run: |
          # 下載 ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          mv ngrok /usr/local/bin/

      - name: Start ngrok TCP tunnel
        run: |
          # 從 GitHub secrets 中獲取 ngrok authtoken
          NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}

          # 使用 authtoken 驗證 ngrok
          ngrok authtoken $NGROK_AUTH_TOKEN

          # 在歐洲區域使用端口 3389（RDP）啟動 ngrok
          ngrok tcp --region eu 3389 &

          # 等待幾秒確保 ngrok 正在運行
          sleep 5

          # 獲取 ngrok 提供的公共 IP 地址
          public_ip=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')

          # 輸出公共 IP 地址
          echo "Public IP Address: $public_ip"

      - name: Keep Alive
        run: |
          # 添加一個長時間運行的命令以保持工作流程運行
          while true; do
            echo "Workflow is running..."
            sleep 43200  # 每隔 12 小時休眠
          done
